# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rye' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rye

  target 'RyeTests' do
    # Pods for testing
	pod 'Quick'
  	pod 'Nimble'
  end

end

target 'RyeExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RyeExample

end
